data_source:
  website: "https://ai.pydantic.dev"

chunks:
  chunk_size:
    pdf: 500
    markdown: 5000
  n_chunks:
    pdf: 5
    markdown: 1

tokenizer:
  model: "sentence-transformers/all-MiniLM-L6-v2"

model:
  llm: "gpt-4o-mini"
  embedding: "text-embedding-ada-002"